package com.codecool.krk.lucidmotors.queststore.enums;

public enum MentorOptions {
    ADD_STUDENT,
    LIST_STUDENTS_WALLETS,
    ADD_QUEST,
    ADD_QUEST_CATEGORY,
    UPDATE_QUEST,
    MARK_BOUGHT_ARTIFACT_AS_USED,
    APPROVE_QUEST_ACHIEVEMENT,
    START_MENTOR_STORE_CONTROLLER,
    SHOW_AVAILABLE_ARTIFACTS,
    ADD_ARTIFACT,
    UPDATE_ARTIFACT,
    ADD_ARTIFACT_CATEGORY
}
